-- Modes file for RUN
return {
    ["Default"]={
        ["autounloadondeathmode"]="Auto",
        ["autodispelmode"]="Off",
        ["subtrustsettingsmode"]="Default",
        ["automagicburstmode"]="Off",
        ["autoaftermathmode"]="Auto",
        ["autorunemode"]="Tenebrae",
        ["autoskillchainmode"]="Off",
        ["autofacemobmode"]="Auto",
        ["autofollowmode"]="Always",
        ["autopullmode"]="Off",
        ["autoengagemode"]="Off",
        ["skillchainprioritymode"]="Prefer",
        ["skillchaindelaymode"]="Off",
        ["maintrustsettingsmode"]="Default",
        ["autobuffmode"]="Auto",
        ["skillchainpartnermode"]="Off",
        ["autotargetmode"]="Off",
        ["engagemode"]="None",
        ["autofoodmode"]="Off",
        ["combatmode"]="Off",
        ["autotrustsmode"]="Off",
        ["autoenmityreductionmode"]="Off",
        ["autotankmode"]="Auto",
        ["ipcmode"]="All",
    }
}