return T{
    [8193] = {id=8193,en="Harlequin Head",ja="汎用ヘッド",enl="Harlequin head",jal="汎用ヘッド",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8194] = {id=8194,en="Valoredge Head",ja="白兵戦ヘッド",enl="Valoredge X-900 head",jal="白兵戦ヘッド",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8195] = {id=8195,en="Sharpshot Head",ja="射撃戦ヘッド",enl="Sharpshot Z-500 head",jal="射撃戦ヘッド",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8196] = {id=8196,en="Stormwaker Head",ja="魔法戦ヘッド",enl="Stormwaker Y-700 head",jal="魔法戦ヘッド",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8197] = {id=8197,en="Soulsoother Head",ja="白魔法戦ヘッド",enl="Soulsoother C-1000 head",jal="白魔法戦ヘッド",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8198] = {id=8198,en="Spiritreaver Head",ja="黒魔法戦ヘッド",enl="Spiritreaver M-400 head",jal="黒魔法戦ヘッド",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8224] = {id=8224,en="Harlequin Frame",ja="汎用フレーム",enl="Harlequin frame",jal="汎用フレーム",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8225] = {id=8225,en="Valoredge Frame",ja="白兵戦フレーム",enl="Valoredge X-900 frame",jal="白兵戦フレーム",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8226] = {id=8226,en="Sharpshot Frame",ja="射撃戦フレーム",enl="Sharpshot Z-500 frame",jal="射撃戦フレーム",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8227] = {id=8227,en="Stormwaker Frame",ja="魔法戦フレーム",enl="Stormwaker Y-700 frame",jal="魔法戦フレーム",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8449] = {id=8449,en="Strobe",ja="ストロボ",enl="strobe",jal="ストロボ",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8450] = {id=8450,en="Tension Spring",ja="Ｔ．スプリング",enl="tension spring",jal="Ｔ．スプリング",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8451] = {id=8451,en="Inhibitor",ja="インヒビター",enl="inhibitor",jal="インヒビター",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8452] = {id=8452,en="Tension Spring II",ja="Ｔ．スプリングII",enl="tension spring II",jal="Ｔ．スプリングII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8453] = {id=8453,en="Attuner",ja="アチューナー",enl="attuner",jal="アチューナー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8454] = {id=8454,en="Reactive Shield",ja="Ｒ．シールド",enl="reactive shield",jal="Ｒ．シールド",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8455] = {id=8455,en="Flame Holder",ja="フレイムホルダー",enl="flame holder",jal="フレイムホルダー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8456] = {id=8456,en="Heat Capacitor",ja="ヒートキャパシター",enl="heat capacitor",jal="ヒートキャパシター",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8457] = {id=8457,en="Strobe II",ja="ストロボII",enl="strobe II",jal="ストロボII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8458] = {id=8458,en="Tension Spring III",ja="Ｔ．スプリングIII",enl="tension spring III",jal="Ｔ．スプリングIII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8459] = {id=8459,en="Inhibitor II",ja="インヒビターII",enl="inhibitor II",jal="インヒビターII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8460] = {id=8460,en="Tension Spring IV",ja="Ｔ．スプリングIV",enl="tension spring IV",jal="Ｔ．スプリングIV",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8461] = {id=8461,en="Heat Capacitor II",ja="Ｈ．キャパシターII",enl="heat capacitor II",jal="Ｈ．キャパシターII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8462] = {id=8462,en="Speedloader",ja="チェインアンプ",enl="speedloader",jal="チェインアンプ",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8463] = {id=8463,en="Speedloader II",ja="チェインアンプII",enl="speedloader II",jal="チェインアンプII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8464] = {id=8464,en="Tension Spring V",ja="Ｔ．スプリングV",enl="tension spring V",jal="Ｔ．スプリングV",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8465] = {id=8465,en="Magniplug",ja="マグニプラッグ",enl="magniplug",jal="マグニプラッグ",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8466] = {id=8466,en="Magniplug II",ja="マグニプラッグII",enl="magniplug II",jal="マグニプラッグII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8481] = {id=8481,en="Mana Booster",ja="マナブースター",enl="mana booster",jal="マナブースター",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8482] = {id=8482,en="Loudspeaker",ja="ラウドスピーカー",enl="loudspeaker",jal="ラウドスピーカー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8483] = {id=8483,en="Scanner",ja="スキャナー",enl="scanner",jal="スキャナー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8484] = {id=8484,en="Loudspeaker II",ja="ラウドスピーカーII",enl="loudspeaker II",jal="ラウドスピーカーII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8485] = {id=8485,en="Tactical Processor",ja="Ｔ．プロセッサー",enl="tactical processor",jal="Ｔ．プロセッサー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8486] = {id=8486,en="Tranquilizer",ja="トランキライザー",enl="tranquilizer",jal="トランキライザー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8487] = {id=8487,en="Ice Maker",ja="アイスメーカー",enl="ice maker",jal="アイスメーカー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8488] = {id=8488,en="Power Cooler",ja="パワークーラー",enl="power cooler",jal="パワークーラー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8489] = {id=8489,en="Loudspeaker III",ja="ラウドスピーカーIII",enl="loudspeaker III",jal="ラウドスピーカーIII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8490] = {id=8490,en="Tranquilizer II",ja="トランキライザーII",enl="tranquilizer II",jal="トランキライザーII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8491] = {id=8491,en="Amplifier",ja="アンプリファイアー",enl="amplifier",jal="アンプリファイアー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8492] = {id=8492,en="Loudspeaker IV",ja="ラウドスピーカーIV",enl="loudspeaker IV",jal="ラウドスピーカーIV",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8493] = {id=8493,en="Tranquilizer III",ja="トランキライザーIII",enl="tranquilizer III",jal="トランキライザーIII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8494] = {id=8494,en="Amplifier II",ja="アンプリファイアII",enl="amplifier II",jal="アンプリファイアII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8495] = {id=8495,en="Loudspeaker V",ja="ラウドスピーカーV",enl="loudspeaker V",jal="ラウドスピーカーV",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8496] = {id=8496,en="Tranquilizer IV",ja="トランキライザーIV",enl="tranquilizer IV",jal="トランキライザーIV",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8497] = {id=8497,en="Arcanoclutch",ja="アルカノクラッチ",enl="arcanoclutch",jal="アルカノクラッチ",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8498] = {id=8498,en="Arcanoclutch II",ja="アルカノクラッチII",enl="arcanoclutch II",jal="アルカノクラッチII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8513] = {id=8513,en="Accelerator",ja="アクセラレーター",enl="accelerator",jal="アクセラレーター",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8514] = {id=8514,en="Scope",ja="スコープ",enl="scope",jal="スコープ",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8515] = {id=8515,en="Pattern Reader",ja="パターンリーダー",enl="pattern reader",jal="パターンリーダー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8516] = {id=8516,en="Accelerator II",ja="アクセラレーターII",enl="accelerator II",jal="アクセラレーターII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8517] = {id=8517,en="Drum Magazine",ja="ドラムマガジン",enl="drum magazine",jal="ドラムマガジン",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8518] = {id=8518,en="Turbo Charger",ja="ターボチャージャー",enl="turbo charger",jal="ターボチャージャー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8519] = {id=8519,en="Replicator",ja="レプリケーター",enl="replicator",jal="レプリケーター",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8520] = {id=8520,en="Barrage Turbine",ja="バラージタービン",enl="barrage turbine",jal="バラージタービン",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8521] = {id=8521,en="Turbo Charger II",ja="Ｔ．チャージャーII",enl="turbo charger II",jal="Ｔ．チャージャーII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8522] = {id=8522,en="Accelerator III",ja="アクセラレーターIII",enl="accelerator III",jal="アクセラレーターIII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8523] = {id=8523,en="Scope II",ja="スコープII",enl="scope II",jal="スコープII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8524] = {id=8524,en="Repeater",ja="リピーター",enl="repeater",jal="リピーター",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8525] = {id=8525,en="Accelerator IV",ja="アクセラレーターIV",enl="accelerator IV",jal="アクセラレーターIV",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8526] = {id=8526,en="Scope III",ja="スコープIII",enl="scope III",jal="スコープIII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8527] = {id=8527,en="Scope IV",ja="スコープIV",enl="scope IV",jal="スコープIV",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8528] = {id=8528,en="Truesights",ja="トゥルーサイツ",enl="truesights",jal="トゥルーサイツ",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8545] = {id=8545,en="Shock Absorber",ja="Ｓ．アブソーバー",enl="shock absorber",jal="Ｓ．アブソーバー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8546] = {id=8546,en="Armor Plate",ja="アーマープレート",enl="armor plate",jal="アーマープレート",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8547] = {id=8547,en="Analyzer",ja="アナライザー",enl="analyzer",jal="アナライザー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8548] = {id=8548,en="Armor Plate II",ja="アーマープレートII",enl="armor plate II",jal="アーマープレートII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8549] = {id=8549,en="Equalizer",ja="イコライザー",enl="equalizer",jal="イコライザー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8550] = {id=8550,en="Schurzen",ja="シュルツン",enl="schurzen",jal="シュルツン",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8551] = {id=8551,en="Hammermill",ja="ハンマーミル",enl="hammermill",jal="ハンマーミル",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8552] = {id=8552,en="Barrier Module II",ja="バリアモジュールII",enl="barrier module II",jal="バリアモジュールII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8553] = {id=8553,en="Shock Absorber II",ja="Ｓ．アブソーバーII",enl="shock absorber II",jal="Ｓ．アブソーバーII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8554] = {id=8554,en="Armor Plate III",ja="アーマープレートIII",enl="armor plate III",jal="アーマープレートIII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8555] = {id=8555,en="Barrier Module",ja="バリアモジュール",enl="barrier module",jal="バリアモジュール",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8556] = {id=8556,en="Armor Plate IV",ja="アーマープレートIV",enl="armor plate IV",jal="アーマープレートIV",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8557] = {id=8557,en="Shock Absorber III",ja="Ｓ．アブソーバーIII",enl="shock absorber III",jal="Ｓ．アブソーバーIII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8577] = {id=8577,en="Stabilizer",ja="スタビライザー",enl="stabilizer",jal="スタビライザー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8578] = {id=8578,en="Volt Gun",ja="ヴォルトガン",enl="volt gun",jal="ヴォルトガン",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8579] = {id=8579,en="Heat Seeker",ja="ヒートシーカー",enl="heat seeker",jal="ヒートシーカー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8580] = {id=8580,en="Stabilizer II",ja="スタビライザーII",enl="stabilizer II",jal="スタビライザーII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8581] = {id=8581,en="Target Marker",ja="ターゲットマーカー",enl="target marker",jal="ターゲットマーカー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8582] = {id=8582,en="Dynamo",ja="ダイナモ",enl="dynamo",jal="ダイナモ",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8583] = {id=8583,en="Coiler",ja="コイラー",enl="coiler",jal="コイラー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8584] = {id=8584,en="Galvanizer",ja="ガルバナイザー",enl="galvanizer",jal="ガルバナイザー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8585] = {id=8585,en="Stabilizer III",ja="スタビライザーIII",enl="stabilizer III",jal="スタビライザーIII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8586] = {id=8586,en="Coiler II",ja="コイラーII",enl="coiler II",jal="コイラーII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8587] = {id=8587,en="Dynamo II",ja="ダイナモII",enl="dynamo II",jal="ダイナモII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8588] = {id=8588,en="Stabilizer IV",ja="スタビライザーIV",enl="stabilizer IV",jal="スタビライザーIV",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8589] = {id=8589,en="Dynamo III",ja="ダイナモIII",enl="dynamo III",jal="ダイナモIII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8590] = {id=8590,en="Stabilizer V",ja="スタビライザーV",enl="stabilizer V",jal="スタビライザーV",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8609] = {id=8609,en="Mana Jammer",ja="マナジャマー",enl="mana jammer",jal="マナジャマー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8610] = {id=8610,en="Heatsink",ja="ヒートシンク",enl="heatsink",jal="ヒートシンク",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8611] = {id=8611,en="Stealth Screen",ja="ステルススクリーン",enl="stealth screen",jal="ステルススクリーン",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8612] = {id=8612,en="Mana Jammer II",ja="マナジャマーII",enl="mana jammer II",jal="マナジャマーII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8613] = {id=8613,en="Mana Channeler",ja="マナチャネラー",enl="mana channeler",jal="マナチャネラー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8614] = {id=8614,en="Condenser",ja="コンデンサー",enl="condenser",jal="コンデンサー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8615] = {id=8615,en="Steam Jacket",ja="スチームジャケット",enl="steam jacket",jal="スチームジャケット",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8616] = {id=8616,en="Percolator",ja="パーコレーター",enl="percolator",jal="パーコレーター",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8617] = {id=8617,en="Mana Jammer III",ja="マナジャマーIII",enl="mana jammer III",jal="マナジャマーIII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8618] = {id=8618,en="Stealth Screen II",ja="Ｓ．スクリーンII",enl="stealth screen II",jal="Ｓ．スクリーンII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8619] = {id=8619,en="Resister",ja="レジスター",enl="resister",jal="レジスター",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8620] = {id=8620,en="Resister II",ja="レジスターII",enl="resister II",jal="レジスターII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8621] = {id=8621,en="Mana Jammer IV",ja="マナジャマーIV",enl="mana jammer IV",jal="マナジャマーIV",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8622] = {id=8622,en="Mana Channeler II",ja="マナチャネラーII",enl="mana channeler II",jal="マナチャネラーII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8641] = {id=8641,en="Auto-Repair Kit",ja="オートリペアキット",enl="auto-repair kit",jal="オートリペアキット",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8642] = {id=8642,en="Flashbulb",ja="フラッシュバルブ",enl="flashbulb",jal="フラッシュバルブ",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8643] = {id=8643,en="Damage Gauge",ja="ダメージゲージ",enl="damage gauge",jal="ダメージゲージ",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8644] = {id=8644,en="Auto-Repair Kit II",ja="Ａ．リペアキットII",enl="auto-repair kit II",jal="Ａ．リペアキットII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8645] = {id=8645,en="Eraser",ja="イレーザー",enl="eraser",jal="イレーザー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8646] = {id=8646,en="Optic Fiber",ja="Ｏ．ファイバー",enl="optic fiber",jal="Ｏ．ファイバー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8648] = {id=8648,en="Vivi-Valve",ja="Ｖ．チューブ",enl="vivi-valve",jal="Ｖ．チューブ",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8649] = {id=8649,en="Vivi-Valve II",ja="Ｖ．チューブII",enl="vivi-valve II",jal="Ｖ．チューブII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8650] = {id=8650,en="Auto-Repair Kit III",ja="Ａ．リペアキットIII",enl="auto-repair kit III",jal="Ａ．リペアキットIII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8651] = {id=8651,en="Arcanic Cell",ja="アカニックセル",enl="arcanic cell",jal="アカニックセル",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8652] = {id=8652,en="Arcanic Cell II",ja="アカニックセルII",enl="arcanic cell II",jal="アカニックセルII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8653] = {id=8653,en="Auto-Repair Kit IV",ja="Ａ．リペアキットIV",enl="auto-repair kit IV",jal="Ａ．リペアキットIV",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8654] = {id=8654,en="Optic Fiber II",ja="Ｏ．ファイバーII",enl="optic fiber II",jal="Ｏ．ファイバーII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8655] = {id=8655,en="Damage Gauge II",ja="ダメージゲージII",enl="damage gauge II",jal="ダメージゲージII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8673] = {id=8673,en="Mana Tank",ja="マナタンク",enl="mana tank",jal="マナタンク",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8674] = {id=8674,en="Mana Converter",ja="マナコンバーター",enl="mana converter",jal="マナコンバーター",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8675] = {id=8675,en="Mana Conserver",ja="マナコンサーバー",enl="mana conserver",jal="マナコンサーバー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8676] = {id=8676,en="Mana Tank II",ja="マナタンクII",enl="mana tank II",jal="マナタンクII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8677] = {id=8677,en="Smoke Screen",ja="スモークスクリーン",enl="smoke screen",jal="スモークスクリーン",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8678] = {id=8678,en="Economizer",ja="エコノマイザー",enl="economizer",jal="エコノマイザー",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8680] = {id=8680,en="Disruptor",ja="ディスラプター",enl="disruptor",jal="ディスラプター",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8681] = {id=8681,en="Mana Tank III",ja="マナタンクIII",enl="mana tank III",jal="マナタンクIII",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8682] = {id=8682,en="Regulator",ja="レギュレーター",enl="regulator",jal="レギュレーター",category="Automaton",flags=0,stack=1,targets=0,type=0},
    [8683] = {id=8683,en="Mana Tank IV",ja="マナタンクIV",enl="mana tank IV",jal="マナタンクIV",category="Automaton",flags=0,stack=1,targets=0,type=0},
}, {"id", "en", "ja", "enl", "jal", "category", "flags", "stack", "targets", "type", "cast_time", "jobs", "level", "races", "slots", "cast_delay", "max_charges", "recast_delay", "shield_size", "damage", "delay", "skill", "ammo_type", "range_type", "item_level", "superior_level"}