-- Supplementary file to res/monster_abilities.lua

return T{
    -- Beast
    [1] = {id=1, en="Behemoth", family="Behemoth", type="Beast", resistances={}},
    [2] = {id=2, en="Buffalo", family="Buffalo", type="Beast", resistances={[5]=1.125}},
    [3] = {id=3, en="Cehuetzi", family="Cehuetzi", type="Beast", resistances={}},
    [4] = {id=4, en="Cerberus", family="Cerberus", type="Beast", resistances={}},
    [5] = {id=5, en="Coeurl", family="Coeurl", type="Beast", resistances={[0]=1.250,[1]=1.250,[2]=1.250,[3]=1.500,[5]=1.250,[6]=1.250,[7]=1.250}},
    [6] = {id=6, en="Dhalmel", family="Dhalmel", type="Beast", resistances={[2]=1.250,[4]=1.250}},
    [7] = {id=7, en="Gnole", family="Gnole", type="Beast", resistances={}},
    [8] = {id=8, en="Manticore", family="Manticore", type="Beast", resistances={[0]=0.500,[1]=1.250,[2]=0.500,[3]=1.250,[4]=1.250,[5]=1.500}},
    [9] = {id=9, en="Marid", family="Marid", type="Beast", resistances={[1]=1.125}},
    [10] = {id=10, en="Opo-opo", family="Opo-opo", type="Beast", resistances={}},
    [11] = {id=11, en="Raaz", family="Raaz", type="Beast", resistances={}},
    [12] = {id=12, en="Rabbit", family="Rabbit", type="Beast", resistances={[4]=1.250,[5]=1.250,[7]=1.250}},
    [13] = {id=13, en="Ram", family="Ram", type="Beast", resistances={}},
    [14] = {id=14, en="Sheep", family="Sheep", type="Beast", resistances={[0]=1.250,[4]=1.250}},
    [15] = {id=15, en="Tiger", family="Tiger", type="Beast", resistances={[0]=1.250,[1]=0.875,[4]=1.250}},
    [16] = {id=16, en="Yztarg", family="Yztarg", type="Beast", resistances={}},
    -- Lizard
    [17] = {id=16, en="Adamantoise", family="Adamantoise", type="Lizard", resistances={}},
    [18] = {id=16, en="Bugard", family="Bugard", type="Lizard", resistances={}},
    [19] = {id=16, en="Eft", family="Eft", type="Lizard", resistances={}},
    [20] = {id=16, en="Gabbrath", family="Gabbrath", type="Lizard", resistances={}},
    [21] = {id=16, en="Hill Lizard", family="Hill Lizard", type="Lizard", resistances={}},
    [22] = {id=16, en="Matamata", family="Matamata", type="Lizard", resistances={}},
    [23] = {id=16, en="Peiste", family="Peiste", type="Lizard", resistances={}},
    [24] = {id=16, en="Raptor", family="Raptor", type="Lizard", resistances={}},
    [25] = {id=16, en="Wivre", family="Wivre", type="Lizard", resistances={}},
    -- Vermin
    [26] = {id=26, en="Antlion", family="Antlion", type="Vermin", resistances={[0]=1.3,[1]=1.5,[4]=1.3,[5]=1.3,[6]=1.3,[7]=1.3}},
    [27] = {id=27, en="Bee", family="Bee", type="Vermin", resistances={[0]=1.25,[1]=1.5,[2]=0.75,[3]=1.25,[4]=1.25,[5]=1.25,[6]=1.25,[7]=1.25}},
    [28] = {id=28, en="Beetle", family="Beetle", type="Vermin", resistances={[0]=1,[1]=1.5,[2]=1,[3]=1,[4]=1,[5]=1,[6]=1.5,[7]=1}},
    [29] = {id=29, en="Bztavian", family="Bztavian", type="Vermin", resistances={}},
    [30] = {id=30, en="Chapuli", family="Chapuli", type="Vermin", resistances={}},
    [31] = {id=31, en="Chigoe", family="Chigoe", type="Vermin", resistances={[0]=1.125,[1]=1.125}},
    [32] = {id=32, en="Crawler", family="Crawler", type="Vermin", resistances={[0]=1.250,[1]=1.500,[2]=1.250,[4]=1.500,[5]=1.250,[7]=1.500}},
    [33] = {id=33, en="Diremite", family="Diremite", type="Vermin", resistances={[5]=1.250,[6]=1.250}},
    [34] = {id=34, en="Fly", family="Fly", type="Vermin", resistances={[0]=1.3,[1]=1.5,[4]=1.3,[5]=1.3,[6]=1.3,[7]=1.3}},
    [35] = {id=35, en="Gnat", family="Gnat", type="Vermin", resistances={}},
    [36] = {id=36, en="Ladybug", family="Ladybug", type="Vermin", resistances={}},
    [37] = {id=37, en="Mantid", family="Mantid", type="Vermin", resistances={}},
    [38] = {id=38, en="Mosquito", family="Mosquito", type="Vermin", resistances={}},
    [39] = {id=39, en="Scorpion", family="Scorpion", type="Vermin", resistances={}},
    [40] = {id=40, en="Spider", family="Spider", type="Vermin", resistances={[1]=1.5,[4]=1.125,[5]=1.25}},
    [41] = {id=41, en="Twitherym", family="Twitherym", type="Vermin", resistances={}},
    [42] = {id=42, en="Wamoura", family="Wamoura", type="Vermin", resistances={}},
    [43] = {id=43, en="Wamouracampa", family="Wamouracampa", type="Vermin", resistances={[0]=0.875,[1]=1.125}},
    -- Plantoid
    [44] = {id=44, en="Belladonna", family="Belladonna", type="Plantoid", resistances={}},
    [45] = {id=45, en="Flytrap", family="Flytrap", type="Plantoid", resistances={}},
    [46] = {id=46, en="Funguar", family="Funguar", type="Plantoid", resistances={}},
    [47] = {id=47, en="Goobbue", family="Goobbue", type="Plantoid", resistances={}},
    [48] = {id=48, en="Leafkin", family="Leafkin", type="Plantoid", resistances={}},
    [49] = {id=49, en="Mandragora", family="Mandragora", type="Plantoid", resistances={}},
    [50] = {id=50, en="Morbol", family="Morbol", type="Plantoid", resistances={}},
    [51] = {id=51, en="Panopt", family="Panopt", type="Plantoid", resistances={}},
    [52] = {id=52, en="Rafflesia", family="Rafflesia", type="Plantoid", resistances={}},
    [53] = {id=53, en="Sabotender", family="Sabotender", type="Plantoid", resistances={}},
    [54] = {id=54, en="Sapling", family="Sapling", type="Plantoid", resistances={[0]=1.250,[6]=0.875,[7]=1.250}},
    [55] = {id=55, en="Snapweed", family="Snapweed", type="Plantoid", resistances={}},
    [56] = {id=56, en="Treant", family="Treant", type="Plantoid", resistances={}},
    [57] = {id=57, en="Yggdreant", family="Yggdreant", type="Plantoid", resistances={}},
    -- Amorph
    [58] = {id=58, en="Acuex", family="Acuex", type="Amorph", resistances={}},
    [59] = {id=59, en="Botulus", family="Botulus", type="Amorph", resistances={}},
    [60] = {id=60, en="Flan", family="Flan", type="Amorph", resistances={}},
    [61] = {id=61, en="Hecteyes", family="Hecteyes", type="Amorph", resistances={}},
    [62] = {id=62, en="Leech", family="Leech", type="Amorph", resistances={}},
    [63] = {id=63, en="Plovid", family="Plovid", type="Amorph", resistances={}},
    [64] = {id=64, en="Sandworm", family="Sandworm", type="Amorph", resistances={}},
    [65] = {id=65, en="Slime", family="Slime", type="Amorph", resistances={}},
    [66] = {id=66, en="Slug", family="Slug", type="Amorph", resistances={}},
    [67] = {id=67, en="Worm", family="Worm", type="Amorph", resistances={}},
    -- Bird
    [68] = {id=68, en="Amphiptere", family="Amphiptere", type="Bird", resistances={}},
    [69] = {id=69, en="Apkallu", family="Apkallu", type="Bird", resistances={[3]=1.125,[4]=0.875,[5]=0.500}},
    [70] = {id=70, en="Bat", family="Bat", type="Bird", resistances={}},
    [71] = {id=71, en="Cockatrice", family="Cockatrice", type="Bird", resistances={[1]=1.250,[2]=1.250,[3]=0.875,}},
    [72] = {id=72, en="Colibri", family="Colibri", type="Bird", resistances={[0]=0.875,[2]=0.500,[3]=0.875,[4]=0.875,[5]=0.875,[7]=0.875}},
    [73] = {id=73, en="Flock Bat", family="Flock Bat", type="Bird", resistances={}},
    [74] = {id=74, en="Greater Bird", family="Greater Bird", type="Bird", resistances={}},
    [75] = {id=75, en="Harpeia", family="Harpeia", type="Bird", resistances={}},
    [76] = {id=76, en="Hippogryph", family="Hippogryph", type="Bird", resistances={}},
    [77] = {id=77, en="Lesser Bird", family="Lesser Bird", type="Bird", resistances={[0]=1.250,[1]=1.500,[4]=1.250,[5]=1.250,[6]=1.250,[7]=1.250}},
    [78] = {id=78, en="Tulfaires", family="Tulfaires", type="Bird", resistances={}},
    [79] = {id=79, en="Waktza", family="Waktza", type="Bird", resistances={}},
    -- Aquan
    [80] = {id=80, en="Crab", family="Crab", type="Aquan", resistances={[0]=1.250,[1]=1.500,[2]=1.250,[3]=1.250,[4]=1.500,[5]=0.750,[6]=1.250,[7]=1.250}},
    [81] = {id=81, en="Craklaw", family="Craklaw", type="Aquan", resistances={}},
    [82] = {id=82, en="Frog", family="Frog", type="Aquan", resistances={}},
    [83] = {id=83, en="Orobon", family="Orobon", type="Aquan", resistances={}},
    [84] = {id=84, en="Pteraketos", family="Pteraketos", type="Aquan", resistances={}},
    [85] = {id=85, en="Pugil", family="Pugil", type="Aquan", resistances={[0]=1.250,[1]=1.500,[2]=1.250,[3]=1.250,[4]=1.500,[5]=0.375,[6]=1.250,[7]=1.250}},
    [86] = {id=86, en="Rockfin", family="Rockfin", type="Aquan", resistances={}},
    [87] = {id=87, en="Sea Monk", family="Sea Monk", type="Aquan", resistances={}},
    [88] = {id=88, en="Ruszor", family="Ruszor", type="Aquan", resistances={}},
    [89] = {id=89, en="Uragnite", family="Uragnite", type="Aquan", resistances={}},
    -- Undead
    -- Arcana
    -- Demon
    -- Dragon
    -- Beastmen
}, {"id", "en", "family", "type", "resistances"}


