project = 'Cylibs'
description = 'Cylibs'
full_description = [[
These are library functions built on top of Windower's core functionality.
]]
file = {'../../util','../../battle','../../entity','../../entity/jobs',exclude = {'../../util/md5.lua','../../util/urlcode.lua','../../util/Modes.lua','../../util/States.lua','../../util/ltn12.lua','../../util/mime.lua'}}
no_summary = true
no_return_or_parms = false
format = 'discount'
